config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
    resources :comments
  end    
  resources :magzines do
    resources :articles
    collection do
      get 'all_magzines'
    end
  end

  resources :comments do
    resources :comments
  end
  devise_for :users, controllers: { sessions: "sessions"}

   root 'home#index'
   get "errors/error_404" => 'errors#error_404' , :as => :four_zero_four

  get '*path', :to => 'errors#error_404'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
  validates_presence_of :body
  
  def article
    return @article if defined?(@article)
    @article = commentable.is_a?(Article) ? commentable : commentable.article
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
	before_filter :get_parent
	
  
  def new
    @comment = @parent.comments.build
    respond_to do |format|
      format.js
      format.html {
        redirect_to root_path
      }
    end
  end

	def create
		@comment = @parent.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.article_id = @parent.is_a?(Article)? @parent.id : @parent.article.id
		@comment.save
	end

  def get_parent
    @parent = Article.find_by_id(params[:article_id]) if params[:article_id]
    @parent = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    respond_to do |format|
    	format.js {
    		unless defined?(@parent)
    			"window.location=#{root_path}"
    		end
    	}
    	format.html {
    		redirect_to root_path unless defined?(@parent)		
    	}
    end
    
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.comments.size == 0
      @comment.destroy
    end

  end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="commentmsg<%=comment.id%>"></div>
<li class="comment">
  <div class="body" style="word-wrap: break-word;
width: 50%">
    <%= comment.body %>
    <%if current_user %>
      <div><strong><%= comment.user.try(:full_name) %></strong><span><%= (comment.user.id == current_user.id) ? (link_to "Remove Comment", comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'}, remote: true, class: "btn") : "" %></span></div>
    <% else %>
      <div><strong><%= comment.user.try(:full_name) %></strong>
    <% end %>
  </div>
  <p><%= link_to 'Add a Reply', new_comment_comment_path(comment), remote: true, class: "btn btn-primary btn-xs" %></p>
  <div id="new_comment<%=comment.id%>"></div>
  <% unless comment.comments.empty? %>
    <ul class="comment_list">
      <%= render :partial => 'comments/comment', :collection => comment.comments.order('created_at DESC') %>
    </ul>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%= form_for [@parent, Comment.new], remote: true do |f| %>
<p id="error-msg"></p>
<p>
  <%= f.label :body, "New comment" %><br/>
  <%= f.text_area :body, class: "form-control", size: "7x7" %>
</p>
<p><%= f.submit "Add comment", class: "btn btn-primary" %></p>
<% end %>

app/views/comments/create.js.erb
<%if @comment.errors.any? %>
	$("#error-msg").html("<%= @comment.errors.full_messages.join(",")%>").addClass("alert alert-success")
<% end %>
<%if @comment.persisted? %>
	$(".comment_list").html("<%= j(render :partial => 'comment', :collection => @comment.article.comments.order('created_at desc')) %>")
	$("#new_article_comment").html("");
<% end %>

app/views/comments/destroy.js.erb
<%if @comment.comments.size == 0 %>
	$(".comment_list").html("<%= j(render :partial => 'comment', :collection => @comment.article.comments.order('created_at desc')) %>")
<% else %>
	$("#commentmsg<%= @comment.id %>").html("Unable to remove comment,Please remove child comment first.")
<% end %>

$("#new_article_comment").html("");

app/views/comments/new.js.erb
<%if @parent.is_a?(Article) %>
	$("#new_article_comment").html("<%= j(render partial: 'form') %>");
<% else %>
	$("#new_comment<%=@parent.id%>").html("<%= j(render partial: 'form') %>");
<% end %>