config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
    resources :comments
  end    
  resources :magzines do
    resources :articles
    collection do
      get 'all_magzines'
    end
  end

  resources :comments do
    resources :comments
  end
  devise_for :users, controllers: { sessions: "sessions"}

   root 'home#index'
   get "errors/error_404" => 'errors#error_404' , :as => :four_zero_four

  get '*path', :to => 'errors#error_404'
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :magzine
	has_many :comments, :as => :commentable
 
	belongs_to :user

  validates_presence_of :body, :title
	validates_uniqueness_of :title
	validates_length_of :title, maximum: 50
	validates_length_of :body, minimum: 50
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = @magzine.articles.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @magzine = Magzine.find(params[:magzine_id])
    @article = @magzine.articles.new
  end

  # GET /articles/1/edit
  def edit
    @magzine = Magzine.find(params[:magzine_id])
    @article = @magzine.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @magzine = Magzine.find(params[:magzine_id])
    @article = @magzine.articles.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to magzine_article_path(@magzine, @article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @magzine = Magzine.find(params[:magzine_id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to magzine_article_path(@magzine, @article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @magzine = Magzine.find(params[:magzine_id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to magzine_url(@magzine), notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :author, :magzine_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for([@magzine, @article]) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", size: "40x7" %>
  </div>
  
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <%#= link_to 'Back', magzine_path(@magzine), class: "btn btn-red", style: "margin-left:10px;" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<script type="text/javascript">
	var id_redirect;
</script>

<!-- Wrapper -->
<div class="wrapper">
    <!-- Topic Header -->
    <div class="topic">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              
            </div>
            <div class="col-sm-8">
              <ol class="breadcrumb pull-right hidden-xs">
                
                <li class="active">Update Article</li>
              </ol>
            </div>
          </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
            <div class="sign-form">
              <div class="sign-inner">
                <h3 class="first-child">Update Article</h3>
                <hr>
                <%= render 'form' %>
                <!-- <br> -->
               
              </div>
            </div>
          </div>
        </div> <!-- / .row -->      
    </div> <!-- / .container -->
</div> <!-- / .wrapper -->
   
<!-- modal -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="invite_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Invite</h4>
      </div>
      <div class="modal-body">
        <p>Enter multiple emails separated by comma(,)</p>
        <div class="divDialogElements">
            <input class="xlarge xlInput form-control" id="xlInput" name="xlInput" type="text" placeholder="Email Address" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="redirectDialog();" id="invite_submit">Invite</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="message_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Message</h4>
      </div>
      <div class="modal-body">
        <p>Invitations for submitting form has been successfully sent.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

	function redirectDialog() {
	    var iddd='#xlInput';
	    if($(iddd).val().trim().length < 1) {
	      $(iddd).attr("placeholder", "* Required");
	      $(iddd).css('color', 'red');
	      $(iddd).css('border', '2px solid red');
	    } else {
	      	$("#invite_submit").css('cursor', 'wait');
	      	// window.location.href = '/invite/'+id_redirect+'?email='+$(iddd).val().trim();
	      	$.ajax({
		        type: 'GET',
		        url: '/invite/'+id_redirect+'?email='+$(iddd).val().trim(),
		        success: function(response) {
		          console.log("Success");
		          $('#invite_submit').css('cursor','pointer');
		          $('#invite_dialog').modal('hide');
		          $('#message_dialog').modal('show');
		        },
		        error: function() {
		          console.log("Error");
		          $('#invite_submit').css('cursor','pointer');
		        }
		    });
	    }
	}

    $(document).ready(function(){
        $('#invite_submit').css('cursor','pointer');
        $("#xlInput").blur(function(){
            if($(this).val().trim().length < 1) {
                $(this).attr("placeholder", "* Required");
                $(this).css('color', 'red');
                $(this).css('border', '2px solid red');
            } else {
                $(this).attr("placeholder", "Email Address");
                $(this).css('color', '#555555');
                $(this).css('border', '2px solid #BBBBBB');
            }
        });

        $("#xlInput").on('input',function() {
        	$(this).attr("placeholder", "Email Address");
            $(this).css('color', '#555555');
            $(this).css('border', '2px solid #BBBBBB');
        });
    });
</script>

app/views/articles/index.html.erb
<%if notice%>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th>Magzine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%if @articles.size > 0 %>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.user.full_name %></td>
        <td><%= article.magzine.title %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) if current_user.id == article.user.id%></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }  if current_user.id == article.user.id%></td>
      </tr>
    <% else %>
      <tr><td colspan="8"> No Article.</td></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<script type="text/javascript">
	var id_redirect;
</script>

<!-- Wrapper -->
<div class="wrapper">
    <!-- Topic Header -->
    <div class="topic">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              
            </div>
            <div class="col-sm-8">
              <ol class="breadcrumb pull-right hidden-xs">
                
                <li class="active">Create Article</li>
              </ol>
            </div>
          </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
            <div class="sign-form">
              <div class="sign-inner">
                <h3 class="first-child">Create Article</h3>
                <hr>
                <%= render 'form' %>
                <!-- <br> -->
               
              </div>
            </div>
          </div>
        </div> <!-- / .row -->      
    </div> <!-- / .container -->
</div> <!-- / .wrapper -->
   
<!-- modal -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="invite_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Invite</h4>
      </div>
      <div class="modal-body">
        <p>Enter multiple emails separated by comma(,)</p>
        <div class="divDialogElements">
            <input class="xlarge xlInput form-control" id="xlInput" name="xlInput" type="text" placeholder="Email Address" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="redirectDialog();" id="invite_submit">Invite</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="message_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Message</h4>
      </div>
      <div class="modal-body">
        <p>Invitations for submitting form has been successfully sent.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

	function redirectDialog() {
	    var iddd='#xlInput';
	    if($(iddd).val().trim().length < 1) {
	      $(iddd).attr("placeholder", "* Required");
	      $(iddd).css('color', 'red');
	      $(iddd).css('border', '2px solid red');
	    } else {
	      	$("#invite_submit").css('cursor', 'wait');
	      	// window.location.href = '/invite/'+id_redirect+'?email='+$(iddd).val().trim();
	      	$.ajax({
		        type: 'GET',
		        url: '/invite/'+id_redirect+'?email='+$(iddd).val().trim(),
		        success: function(response) {
		          console.log("Success");
		          $('#invite_submit').css('cursor','pointer');
		          $('#invite_dialog').modal('hide');
		          $('#message_dialog').modal('show');
		        },
		        error: function() {
		          console.log("Error");
		          $('#invite_submit').css('cursor','pointer');
		        }
		    });
	    }
	}

    $(document).ready(function(){
        $('#invite_submit').css('cursor','pointer');
        $("#xlInput").blur(function(){
            if($(this).val().trim().length < 1) {
                $(this).attr("placeholder", "* Required");
                $(this).css('color', 'red');
                $(this).css('border', '2px solid red');
            } else {
                $(this).attr("placeholder", "Email Address");
                $(this).css('color', '#555555');
                $(this).css('border', '2px solid #BBBBBB');
            }
        });

        $("#xlInput").on('input',function() {
        	$(this).attr("placeholder", "Email Address");
            $(this).css('color', '#555555');
            $(this).css('border', '2px solid #BBBBBB');
        });
    });
</script>

app/views/articles/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">    
        <%if notice%>
          <p id="notice" class="alert alert-success"><%= notice %></p>
        <% end %>

        <p>
          <strong>Title:</strong>
          <%= @article.title %>
        </p>

        <p style="width:50%;word-break:break-word;">
          <strong>Body:</strong>
          <%= @article.body %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= @article.user.full_name %>
        </p>

        <p>
          <strong>Magzine:</strong>
          <%= @article.magzine.try(:title) %>
        </p>
        <%if current_user.present? and current_user.id == @article.user.id %>
          <%= link_to 'Edit', edit_magzine_article_path(@article.magzine, @article), class: "btn btn-xs btn-blue" %> |
        <% end %>
        <%= link_to 'Back', magzine_path(@article.magzine), class: "btn btn-xs btn-danger" %> |
        <%= link_to 'Add Comment', new_article_comment_path(@article), remote: true, class: "btn btn-xs btn-danger" %>
        <div id="new_article_comment"></div>

        <ul class="comment_list">
          <%= render :partial => 'comments/comment', :collection => @article.comments.order('created_at DESC') %>
        </ul>
      </div>
    </div>
  </div>
</div>