config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
    resources :comments
  end    
  resources :magzines do
    resources :articles
    collection do
      get 'all_magzines'
    end
  end

  resources :comments do
    resources :comments
  end
  devise_for :users, controllers: { sessions: "sessions"}

   root 'home#index'
   get "errors/error_404" => 'errors#error_404' , :as => :four_zero_four

  get '*path', :to => 'errors#error_404'
end

app/models/magzine.rb
class Magzine < ActiveRecord::Base
	belongs_to :user
	has_many :articles
	validates :title, :description, presence: true
	validates_uniqueness_of :title
	validates_length_of :title, maximum: 50
end

app/controllers/magzines_controller.rb
class MagzinesController < ApplicationController
  before_action :set_magzine, only: [ :edit, :update, :destroy]
  before_action :check_user, except: [:show, :new, :create, :all_magzines, :index]
  before_action :authenticate_user!,  only: [:new, :edit, :update, :destroy]

  # GET /magzines
  # GET /magzines.json

  def index
    @magzines = current_user.magzines
  end

  def all_magzines
    @magzines = Magzine.all
  end



  # GET /magzines/1
  # GET /magzines/1.json
  def show
    @magzine = Magzine.find(params[:id])
    @articles = @magzine.articles
  end

  # GET /magzines/new
  def new
    @magzine = Magzine.new
  end

  # GET /magzines/1/edit
  def edit
  end

  # POST /magzines
  # POST /magzines.json
  def create
    @magzine = current_user.magzines.new(magzine_params)

    respond_to do |format|
      if @magzine.save
        format.html { redirect_to @magzine, notice: 'Magzine was successfully created.' }
        format.json { render :show, status: :created, location: @magzine }
      else
        format.html { render :new }
        format.json { render json: @magzine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magzines/1
  # PATCH/PUT /magzines/1.json
  def update
    respond_to do |format|
      if @magzine.update(magzine_params)
        format.html { redirect_to @magzine, notice: 'Magzine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magzine }
      else
        format.html { render :edit }
        format.json { render json: @magzine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magzines/1
  # DELETE /magzines/1.json
  def destroy
    @magzine.destroy
    respond_to do |format|
      format.html { redirect_to magzines_url, notice: 'Magzine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magzine
      @magzine = current_user.magzines.find(params[:id])
    end

    def check_user
      @magzine = current_user.magzines.find(params[:id])
      redirect_to magzines_url , notice: "You are not authorized to edit this magzine" if @magzine.user_id != current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magzine_params
      params.require(:magzine).permit(:title, :description, :user_id)
    end
end

app/helpers/magzines_helper.rb
module MagzinesHelper
end

app/views/magzines/_article_list.html.erb
<div class="wrapper">

  <div class="container">
    <div class="row">
      <div class="col-md-9 col-md-offset-1 col-sm-8 col-sm-offset-2">    

        <div class="table-responsive">
         

          <h1>Articles</h1>
          <div>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Body</th>
                  <th>Author</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
              <%if @articles.size > 0 %>
                <% @articles.each do |article| %>
                  <tr>
                    <td style="width:25%;"><%= article.title %></td>
                    <td style="width:35%;word-break:break-word;"><%= article.body %></td>
                    <td style="width:10%;"><%= article.user.full_name.present? ? article.user.full_name : article.user.email %></td>
                    <td><%= link_to 'Show', magzine_article_path(@magzine, article) %>
                      <%if current_user and (current_user.id == article.user.id) %>
                        <%= link_to 'Edit', edit_magzine_article_path(@magzine, article) %>
                        <%= link_to 'Destroy', magzine_article_path(@magzine, article), method: :delete, data: { confirm: 'Are you sure?' } %></td
                    <% end %>
                  </tr>
                <% end %>
                <% else %>
                  <tr>
                    <td colspan="5">Magazine has not article.</td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/magzines/_form.html.erb
<%= form_for(@magzine) do |f| %>
  <% if @magzine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magzine.errors.count, "error") %> prohibited this magzine from being saved:</h2>

      <ul>
      <% @magzine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", autocomplete: "off" %>

  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", autocomplete: "off", size: "40x7" %>
  </div>
  
  <div class="form-group">
    <%= f.submit :"Create Magzine", class: "btn btn-primary" %>
    <%= link_to 'Back', magzines_path, class: "btn btn-red", style: "margin-left:10px;" %>
  </div>
<% end %>

app/views/magzines/all_magzines.html.erb
<div class="wrapper">

  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">    

      <div class="table-responsive">
        <%if notice%>
          <p id="notice" class="alert alert-success"><%= notice %></p>
        <% end %>

        <h1>Listing Magzines</h1>
        <div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>User</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @magzines.each do |magzine| %>
              <tr>
                <td><%= magzine.title %></td>
                <td><%= magzine.description %></td>
                <td><%= magzine.user.full_name.present? ? magzine.user.full_name : magzine.user.email %></td>
                <td><%= link_to 'Show', magzine %>
                
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

          <%= link_to 'New Magzine', new_magzine_path, class: "btn btn-red" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/magzines/edit.html.erb
<h1>Edit Magzine</h1>

<script type="text/javascript">
	var id_redirect;
</script>

<!-- Wrapper -->
<div class="wrapper">
    <!-- Topic Header -->
    <div class="topic">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              
            </div>
            <div class="col-sm-8">
              <ol class="breadcrumb pull-right hidden-xs">
                
                <li class="active">Create Magzine</li>
              </ol>
            </div>
          </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
            <div class="sign-form">
              <div class="sign-inner">
                <h3 class="first-child">Create Magzine</h3>
                <hr>
                <%= render 'form' %>
                <!-- <br> -->
               
              </div>
            </div>
          </div>
        </div> <!-- / .row -->      
    </div> <!-- / .container -->
</div> <!-- / .wrapper -->
   
<!-- modal -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="invite_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Invite</h4>
      </div>
      <div class="modal-body">
        <p>Enter multiple emails separated by comma(,)</p>
        <div class="divDialogElements">
            <input class="xlarge xlInput form-control" id="xlInput" name="xlInput" type="text" placeholder="Email Address" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="redirectDialog();" id="invite_submit">Invite</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="message_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Message</h4>
      </div>
      <div class="modal-body">
        <p>Invitations for submitting form has been successfully sent.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

	function redirectDialog() {
	    var iddd='#xlInput';
	    if($(iddd).val().trim().length < 1) {
	      $(iddd).attr("placeholder", "* Required");
	      $(iddd).css('color', 'red');
	      $(iddd).css('border', '2px solid red');
	    } else {
	      	$("#invite_submit").css('cursor', 'wait');
	      	// window.location.href = '/invite/'+id_redirect+'?email='+$(iddd).val().trim();
	      	$.ajax({
		        type: 'GET',
		        url: '/invite/'+id_redirect+'?email='+$(iddd).val().trim(),
		        success: function(response) {
		          console.log("Success");
		          $('#invite_submit').css('cursor','pointer');
		          $('#invite_dialog').modal('hide');
		          $('#message_dialog').modal('show');
		        },
		        error: function() {
		          console.log("Error");
		          $('#invite_submit').css('cursor','pointer');
		        }
		    });
	    }
	}

    $(document).ready(function(){
        $('#invite_submit').css('cursor','pointer');
        $("#xlInput").blur(function(){
            if($(this).val().trim().length < 1) {
                $(this).attr("placeholder", "* Required");
                $(this).css('color', 'red');
                $(this).css('border', '2px solid red');
            } else {
                $(this).attr("placeholder", "Email Address");
                $(this).css('color', '#555555');
                $(this).css('border', '2px solid #BBBBBB');
            }
        });

        $("#xlInput").on('input',function() {
        	$(this).attr("placeholder", "Email Address");
            $(this).css('color', '#555555');
            $(this).css('border', '2px solid #BBBBBB');
        });
    });
</script>

app/views/magzines/index.html.erb
<div class="wrapper">

  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">    
        <div class="table-responsive">
          <%if notice %>
            <p id="notice" class="alert alert-success"><%= notice %></p>
          <% end %>

          <h1>Listing Magzines</h1>
          <div>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Title</th>
                <th>Description</th>
                <th>User</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <%if @magzines.size > 0 %>
              <% @magzines.each do |magzine| %>
                <tr>
                  <td style="width:20%"><%= magzine.title %></td>
                  <td style="width:35%;word-break:break-word;"><%= magzine.description %></td>
                  <td style="width:30%"><%= magzine.user.full_name.present? ? magzine.user.full_name : magzine.user.email %></td>
                  <td><%= link_to 'Show', magzine %>
                  <%= link_to 'Edit', edit_magzine_path(magzine) %>
                  <%= link_to 'Destroy', magzine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
              <% else %>
                <tr>
                  <td colspan="3">No Magazine available.</td>
                </tr>

              <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'New Magzine', new_magzine_path, class: "btn btn-red" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/magzines/new.html.erb
<h1>New Magzine</h1>

<script type="text/javascript">
	var id_redirect;
</script>

<!-- Wrapper -->
<div class="wrapper">
    <!-- Topic Header -->
    <div class="topic">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              
            </div>
            <div class="col-sm-8">
              <ol class="breadcrumb pull-right hidden-xs">
                
                <li class="active">Create Magzine</li>
              </ol>
            </div>
          </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
            <div class="sign-form">
              <div class="sign-inner">
                <h3 class="first-child">Create Magzine</h3>
                <hr>
                <%= render 'form' %>
                <!-- <br> -->
               
              </div>
            </div>
          </div>
        </div> <!-- / .row -->      
    </div> <!-- / .container -->
</div> <!-- / .wrapper -->
   
<!-- modal -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="invite_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Invite</h4>
      </div>
      <div class="modal-body">
        <p>Enter multiple emails separated by comma(,)</p>
        <div class="divDialogElements">
            <input class="xlarge xlInput form-control" id="xlInput" name="xlInput" type="text" placeholder="Email Address" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="redirectDialog();" id="invite_submit">Invite</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="message_dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Message</h4>
      </div>
      <div class="modal-body">
        <p>Invitations for submitting form has been successfully sent.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

	function redirectDialog() {
	    var iddd='#xlInput';
	    if($(iddd).val().trim().length < 1) {
	      $(iddd).attr("placeholder", "* Required");
	      $(iddd).css('color', 'red');
	      $(iddd).css('border', '2px solid red');
	    } else {
	      	$("#invite_submit").css('cursor', 'wait');
	      	// window.location.href = '/invite/'+id_redirect+'?email='+$(iddd).val().trim();
	      	$.ajax({
		        type: 'GET',
		        url: '/invite/'+id_redirect+'?email='+$(iddd).val().trim(),
		        success: function(response) {
		          console.log("Success");
		          $('#invite_submit').css('cursor','pointer');
		          $('#invite_dialog').modal('hide');
		          $('#message_dialog').modal('show');
		        },
		        error: function() {
		          console.log("Error");
		          $('#invite_submit').css('cursor','pointer');
		        }
		    });
	    }
	}

    $(document).ready(function(){
        $('#invite_submit').css('cursor','pointer');
        $("#xlInput").blur(function(){
            if($(this).val().trim().length < 1) {
                $(this).attr("placeholder", "* Required");
                $(this).css('color', 'red');
                $(this).css('border', '2px solid red');
            } else {
                $(this).attr("placeholder", "Email Address");
                $(this).css('color', '#555555');
                $(this).css('border', '2px solid #BBBBBB');
            }
        });

        $("#xlInput").on('input',function() {
        	$(this).attr("placeholder", "Email Address");
            $(this).css('color', '#555555');
            $(this).css('border', '2px solid #BBBBBB');
        });
    });
</script>

app/views/magzines/show.html.erb
<div class="wrapper">

  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">    
        <%if notice%>
          <p id="notice" class="alert alert-success"><%= notice %></p>
        <% end %>

        <p>
          <strong>Title:</strong>
          <%= @magzine.title %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @magzine.description %>
        </p>

        <p>
          <strong> Author: </strong>
          <%= @magzine.user.full_name %>
        </p>

        <% if @articles.size > 0 %>
        		<%= render partial: "article_list" %>
        <% else %>
           <div> Magzine has no article.</div>
        <% end %>
        <%if current_user && current_user.id == @magzine.user.id %>
         <%= link_to "New Article", new_magzine_article_path(@magzine),class: "btn btn-blue btn-xs"  %> |
          <%= link_to 'Edit', edit_magzine_path(@magzine), class: "btn btn-xs btn-danger" %> |

        <% end %>
        <%= link_to 'Back', current_user.present? ? magzines_path : root_path , class: "btn btn-xs btn-danger" %>
  
      </div>
    </div>
  </div>
</div>